### PR TITLE
Make parsing independent from caption format

### LINKED ISSUE #13: Field's width is restricted to exactly 8 columns
## Summary

Application fails when number of columns differs from 8.

## Steps to reproduce

1. Edit current state to size 9x6.
2. Start application.

**Expected behaviour:** application is running.
**Actual behaviour:** exception is thrown.

## Suggested solution

The bug is tracked to parsing that assumes the game caption length being equal to the field length that is valid only for 8-columns fields. Suggested solution is to make parsing independent from caption length.
Sample of a larger game field: [current_state.txt](https://github.com/Jiwan/meta_crush_saga/files/3468262/current_state.txt)

### PR DESCRIPTION
**Pull request by aexg**
Resolves #13 - bug that limited game to 8-columns fields.

### CODE REVIEW

**Review by Jiwan — APPROVED** [review]
This makes a lot of sense!

File: parser.hpp [hunk 1]
```diff
@@ -119,13 +120,15 @@ CONSTEXPR CandyState decode_candy_state(char up_char)
...
-constexpr int row_padding = 5;    // space, pipe, pipe, space, newline
-constexpr int noncandy_rows = 3;  // title, border, border
+constexpr int row_padding = 5;  // space, pipe, pipe, space, newline
 
 constexpr auto parse_board_parameters(auto str)
 {
-    BoardParameters ret{ 0, 0, 0, 0 };
+    BoardParameters ret{ 0, 0, 0, 0, 0 };
+
+    constexpr int noncandy_rows = 2;                       // border, border
```
Comment (Jiwan) [inline parser.hpp:129]: Nice comments here. It helps a lot to understand the reason behind these magic numbers :+1:

Comment (aexg) [reply parser.hpp:129]: Just followed existing pattern :-)
